###### Application Specific for ViTs ######
dataset: 'CIFAR10' # options: CIFAR100, CIFAR10, ImageNet, TinyImageNet
network: 'swin_t' # options: see model_choices.txt
optimizer: 'AdaFisherW' # or AdaFisherW
scheduler: 'CosineAnnealingLR' #'CosineAnnealingLR' # options: see scheduler_choices.txt

###### Suggested Tune ######
init_lr: 0.01
early_stop_threshold: -1 #  set to -1 if you wish not to use early stop,
                         # or equally, set to a high value.
optimizer_kwargs:  # named-kwargs to pass to optimizer.
  weight_decay: 0.05
  beta3: 0.91
  Lambda: 0.001
  TCov: 10
scheduler_kwargs: # named-kwargs to pass to scheduler.
  T_max: 200
cutout: False
n_holes: 1
cutout_length: 16

###### Suggested Default ######
n_trials: 1
num_workers: 16
max_epochs: 50
mini_batch_size: 256
loss: 'cross_entropy' # options: cross_entropy
early_stop_patience: 10 # epoch window to consider when deciding whether to stop
